#%RAML 1.0
title: This API is for Meraki Scanning REST Calls
baseUri: meraki

/users:
  get:
    description: Retrieve a list of all the users
    responses:
      200:
        body:
          application/json:
            
